// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSMAGA_ZALICZENIE.Contexts;

#nullable disable

namespace SSMAGAZALICZENIE.Migrations
{
    [DbContext(typeof(CzarterContext))]
    [Migration("20221123212650_Mig1")]
    partial class Mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SSMAGA_ZALICZENIE.Models.AdminModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("uname")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SSMAGA_ZALICZENIE.Models.OfertaModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<int>("Il_Os")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zdjecie")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.HasKey("ID");

                    b.ToTable("Oferta");
                });

            modelBuilder.Entity("SSMAGA_ZALICZENIE.Models.RezerwacjeModel", b =>
                {
                    b.Property<int>("ID_REZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_REZ"));

                    b.Property<DateTime>("DATA_KON")
                        .HasColumnType("date");

                    b.Property<DateTime>("DATA_POCZ")
                        .HasColumnType("date");

                    b.Property<int>("ID_JACHT")
                        .HasColumnType("int");

                    b.Property<int>("OfertaID")
                        .HasColumnType("int");

                    b.HasKey("ID_REZ");

                    b.HasIndex("OfertaID");

                    b.ToTable("Rezerwacje");
                });

            modelBuilder.Entity("SSMAGA_ZALICZENIE.Models.RezerwacjeModel", b =>
                {
                    b.HasOne("SSMAGA_ZALICZENIE.Models.OfertaModel", "Oferta")
                        .WithMany("Rezerwacje")
                        .HasForeignKey("OfertaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("SSMAGA_ZALICZENIE.Models.OfertaModel", b =>
                {
                    b.Navigation("Rezerwacje");
                });
#pragma warning restore 612, 618
        }
    }
}
